/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LibAccessControl__factory } from "./LibAccessControl__factory";
export { LibDiamond__factory } from "./LibDiamond__factory";
