/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IAutomateInterface extends utils.Interface {
  functions: {
    "depositGelatoFunds()": FunctionFragment;
    "getGelatoAddresses()": FunctionFragment;
    "getMinimumAppGelatoBalance()": FunctionFragment;
    "setGelatoContracts(address)": FunctionFragment;
    "setMinimumAppGelatoBalance(uint256)": FunctionFragment;
    "withdrawGelatoFunds(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositGelatoFunds"
      | "getGelatoAddresses"
      | "getMinimumAppGelatoBalance"
      | "setGelatoContracts"
      | "setMinimumAppGelatoBalance"
      | "withdrawGelatoFunds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositGelatoFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGelatoAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumAppGelatoBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGelatoContracts",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumAppGelatoBalance",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawGelatoFunds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositGelatoFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGelatoAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumAppGelatoBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGelatoContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumAppGelatoBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawGelatoFunds",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAutomate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAutomateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositGelatoFunds(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getGelatoAddresses(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, string]>;

    getMinimumAppGelatoBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    setGelatoContracts(
      _ops: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinimumAppGelatoBalance(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawGelatoFunds(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  depositGelatoFunds(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getGelatoAddresses(
    overrides?: CallOverrides
  ): Promise<[string, string, string, string, string]>;

  getMinimumAppGelatoBalance(overrides?: CallOverrides): Promise<BigNumber>;

  setGelatoContracts(
    _ops: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinimumAppGelatoBalance(
    _value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawGelatoFunds(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositGelatoFunds(overrides?: CallOverrides): Promise<void>;

    getGelatoAddresses(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, string]>;

    getMinimumAppGelatoBalance(overrides?: CallOverrides): Promise<BigNumber>;

    setGelatoContracts(
      _ops: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinimumAppGelatoBalance(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawGelatoFunds(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    depositGelatoFunds(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getGelatoAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumAppGelatoBalance(overrides?: CallOverrides): Promise<BigNumber>;

    setGelatoContracts(
      _ops: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinimumAppGelatoBalance(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawGelatoFunds(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositGelatoFunds(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getGelatoAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinimumAppGelatoBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setGelatoContracts(
      _ops: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinimumAppGelatoBalance(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawGelatoFunds(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
