/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUtility,
  IUtilityInterface,
} from "../../../../contracts/interfaces/utils/IUtility";

const _abi = [
  {
    inputs: [],
    name: "getNativeBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdrawNativeBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUtility__factory {
  static readonly abi = _abi;
  static createInterface(): IUtilityInterface {
    return new utils.Interface(_abi) as IUtilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUtility {
    return new Contract(address, _abi, signerOrProvider) as IUtility;
  }
}
