/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface LibAutomateInterface extends utils.Interface {
  functions: {
    "AUTOBOT_PROXY_FACTORY()": FunctionFragment;
    "GELATO_FEE()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "AUTOBOT_PROXY_FACTORY" | "GELATO_FEE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AUTOBOT_PROXY_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GELATO_FEE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTOBOT_PROXY_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GELATO_FEE", data: BytesLike): Result;

  events: {};
}

export interface LibAutomate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibAutomateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    AUTOBOT_PROXY_FACTORY(overrides?: CallOverrides): Promise<[string]>;

    GELATO_FEE(overrides?: CallOverrides): Promise<[string]>;
  };

  AUTOBOT_PROXY_FACTORY(overrides?: CallOverrides): Promise<string>;

  GELATO_FEE(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    AUTOBOT_PROXY_FACTORY(overrides?: CallOverrides): Promise<string>;

    GELATO_FEE(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    AUTOBOT_PROXY_FACTORY(overrides?: CallOverrides): Promise<BigNumber>;

    GELATO_FEE(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    AUTOBOT_PROXY_FACTORY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GELATO_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
