/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  Test3Facet2,
  Test3Facet2Interface,
} from "../../../contracts/tests/Test3Facet2";

const _abi = [
  {
    inputs: [],
    name: "test3Func1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b68061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ebfa4bcc14602d575b600080fd5b60336047565b604051603e91906067565b60405180910390f35b60006002905090565b6000819050919050565b6061816050565b82525050565b6000602082019050607a6000830184605a565b9291505056fea2646970667358221220fa8d9015763e9ef2a558f5c9d17d2c2b72a97ce49d3f9c04b79dccd873dfd26064736f6c63430008120033";

type Test3Facet2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Test3Facet2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Test3Facet2__factory extends ContractFactory {
  constructor(...args: Test3Facet2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Test3Facet2> {
    return super.deploy(overrides || {}) as Promise<Test3Facet2>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Test3Facet2 {
    return super.attach(address) as Test3Facet2;
  }
  override connect(signer: Signer): Test3Facet2__factory {
    return super.connect(signer) as Test3Facet2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Test3Facet2Interface {
    return new utils.Interface(_abi) as Test3Facet2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Test3Facet2 {
    return new Contract(address, _abi, signerOrProvider) as Test3Facet2;
  }
}
