/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InitTest } from "./InitTest";
export type { Test1Facet } from "./Test1Facet";
export type { Test2Facet } from "./Test2Facet";
export type { Test3Facet } from "./Test3Facet";
export type { Test3Facet2 } from "./Test3Facet2";
export type { Test4Facet } from "./Test4Facet";
export type { Test5Facet } from "./Test5Facet";
